feature_names = """
    android-game-activity (default)
    android_shared_stdcxx (default)
    animation (default)
    async_executor (default)
    bevy_anti_alias (default)
    bevy_asset (default)
    bevy_audio (default)
    bevy_camera (default)
    bevy_color (default)
    bevy_core_pipeline (default)
    bevy_gilrs (default)
    bevy_gizmos (default)
    bevy_gltf (default)
    bevy_image (default)
    bevy_input_focus (default)
    bevy_light (default)
    bevy_log (default)
    bevy_mesh (default)
    bevy_mesh_picking_backend (default)
    bevy_pbr (default)
    bevy_picking (default)
    bevy_post_process (default)
    bevy_render (default)
    bevy_scene (default)
    bevy_shader (default)
    bevy_sprite (default)
    bevy_sprite_picking_backend (default)
    bevy_sprite_render (default)
    bevy_state (default)
    bevy_text (default)
    bevy_ui (default)
    bevy_ui_picking_backend (default)
    bevy_ui_render (default)
    bevy_window (default)
    bevy_winit (default)
    custom_cursor (default)
    debug (default)
    default_font (default)
    hdr (default)
    ktx2 (default)
    multi_threaded (default)
    png (default)
    reflect_auto_register (default)
    smaa_luts (default)
    std (default)
    sysinfo_plugin (default)
    tonemapping_luts (default)
    vorbis (default)
    wayland (default)
    webgl2 (default)
    x11 (default)
    zstd_rust (default)
"""

feature_names = feature_names.replace(" (default)", "\n").splitlines()
# print(feature_names)
feature_names = [ name.strip() for name in feature_names if name.strip() ]
# print(feature_names)

print("[")

for name in feature_names:
    name = f"bevy/{name}"
    print(f"\t\"{name}\",")

print("]")

